name: Project Build MacOs

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest
    timeout-minutes: 180

    steps:

      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: set up LOCAL_PROPERTIES
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" > ./local.properties

      - name: generate Ksp metadata
        run: ./gradlew kspKotlinMetadata

      - name: build iosArm64 with Gradle
        run: cd iosApp && xcodebuild -workspace ./iosApp.xcworkspace -scheme iosApp -configuration Debug -destination 'platform=iOS Simulator,OS=18.2,name=iPhone 16' CODE_SIGNING_ALLOWED='NO'