name: Project Build MacOs

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: set up LOCAL_PROPERTIES
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" > ./local.properties

      - name: Build with Gradle
        run: ./gradlew iosArm64Binaries